// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYIIGZBqfb8OzsfDIosK3VVsWy1X4eCvY',
    appId: '1:338998657373:web:24158a3e35a6348a9a28b4',
    messagingSenderId: '338998657373',
    projectId: 'my-iot-project-g01-43',
    authDomain: 'my-iot-project-g01-43.firebaseapp.com',
    storageBucket: 'my-iot-project-g01-43.firebasestorage.app',
    measurementId: 'G-K4VD8K7DKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACHWHcfV0sQ36EzGFc88Np2JD7NT60BFU',
    appId: '1:338998657373:android:2a3a482a221098679a28b4',
    messagingSenderId: '338998657373',
    projectId: 'my-iot-project-g01-43',
    storageBucket: 'my-iot-project-g01-43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRvYUo_4EIiO7PEgEOdhYCogK60LUF4Y',
    appId: '1:338998657373:ios:667cfedd15bd3d299a28b4',
    messagingSenderId: '338998657373',
    projectId: 'my-iot-project-g01-43',
    storageBucket: 'my-iot-project-g01-43.firebasestorage.app',
    iosBundleId: 'com.example.authBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRvYUo_4EIiO7PEgEOdhYCogK60LUF4Y',
    appId: '1:338998657373:ios:667cfedd15bd3d299a28b4',
    messagingSenderId: '338998657373',
    projectId: 'my-iot-project-g01-43',
    storageBucket: 'my-iot-project-g01-43.firebasestorage.app',
    iosBundleId: 'com.example.authBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYIIGZBqfb8OzsfDIosK3VVsWy1X4eCvY',
    appId: '1:338998657373:web:a06244a3ed0e3fd89a28b4',
    messagingSenderId: '338998657373',
    projectId: 'my-iot-project-g01-43',
    authDomain: 'my-iot-project-g01-43.firebaseapp.com',
    storageBucket: 'my-iot-project-g01-43.firebasestorage.app',
    measurementId: 'G-NHQ6ZS9DV8',
  );
}
